name: Build Debian Packages
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update                                  \
            && sudo apt-get -y install --no-install-recommends \
              build-essential                                  \
              xz-utils                                         \
              debhelper                                        \
              dh-exec                                          \
              dh-golang                                        \
              golang-go                                        \
              golang-any                                       \
              golang-github-pkg-errors-dev                     \
              golang-github-urfave-cli-dev                     \
              golang-golang-x-crypto-dev                       \
              golang-golang-x-sys-dev                          \
              golang-goprotobuf-dev                            \
              libpam0g-dev                                     \
              m4
      - run: ./scripts/build-packages.sh
